---
services:
  gateway:
    container_name: gateway
    image: gateway
    restart: always
    build:
      context: .
      dockerfile: Gateway.WebApi/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASP_ENV} 
      PAYMENT_API_KEY: ${API_KEY}
    networks:
      - joystore
    ports:
      - "127.0.0.1:8080:8080"

  panel:
    container_name: panel
    image: panel
    restart: always
    build:
      context: .
      dockerfile: Auth.WebApi/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASP_ENV} 
    networks:
      - joystore
    ports:
      - "127.0.0.1:8088:8080"

networks:
  joystore:
    external: true
