<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\Business.Data\Business.Data.csproj" />
		<ProjectReference Include="..\DataBaseToAccess\DataBaseToAccess.csproj" />
		<ProjectReference Include="..\Service.Application\Service.Application.csproj" />
	</ItemGroup>
</Project>
