// <auto-generated />
using System;
using DataBaseToAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataBaseToAccess.Migrations
{
    [DbContext(typeof(BaseDbContext))]
    [Migration("20250406173813_adminFix")]
    partial class adminFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Business.Data.Models.AddOn", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CusaCodeTr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CusaCodeUa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GroupAddOnGuid")
                        .HasColumnType("uuid");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Platform")
                        .HasColumnType("text");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Guid");

                    b.HasIndex("GameId");

                    b.HasIndex("GroupAddOnGuid");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("AddOns");
                });

            modelBuilder.Entity("Business.Data.Models.Admin", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Guid");

                    b.HasIndex("RoleId");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("Business.Data.Models.Cart", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Guid");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("Business.Data.Models.CartItem", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CartId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.HasKey("Guid");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("Business.Data.Models.Edition", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CusaCodeTr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CusaCodeUa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EditionName")
                        .HasColumnType("text");

                    b.Property<string>("EditionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Features")
                        .HasColumnType("text");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<string>("Platform")
                        .HasColumnType("text");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("Release")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Subscription")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Guid");

                    b.HasIndex("GameId");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Editions");
                });

            modelBuilder.Entity("Business.Data.Models.Favorite", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Guid");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("Business.Data.Models.FavoriteItem", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FavoriteId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.HasKey("Guid");

                    b.HasIndex("FavoriteId");

                    b.HasIndex("ProductId");

                    b.ToTable("FavoriteItems");
                });

            modelBuilder.Entity("Business.Data.Models.Game", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConceptId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<string>("Languages")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Popular")
                        .HasColumnType("text");

                    b.HasKey("Guid");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Business.Data.Models.Geners", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Guid");

                    b.ToTable("Gener");
                });

            modelBuilder.Entity("Business.Data.Models.GenersToEdition", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EditionGuid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EdtitonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GenerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GenersGuid")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.HasKey("Guid");

                    b.HasIndex("EditionGuid");

                    b.HasIndex("GenersGuid");

                    b.ToTable("GenersToEdition");
                });

            modelBuilder.Entity("Business.Data.Models.GroupAddOn", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FilePathImage")
                        .HasColumnType("text");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Guid");

                    b.ToTable("GroupAddOns");
                });

            modelBuilder.Entity("Business.Data.Models.LoyaltyCashback", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Percent")
                        .HasColumnType("numeric");

                    b.HasKey("Guid");

                    b.ToTable("LoyaltyCashbacks");
                });

            modelBuilder.Entity("Business.Data.Models.LoyaltyCurrency", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BalanceJoy")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BalanceJoyPlus")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.HasKey("Guid");

                    b.ToTable("LoyaltyCurrencies");
                });

            modelBuilder.Entity("Business.Data.Models.LoyaltyOrder", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("AmountByJoyPlus")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("AmountByRub")
                        .HasColumnType("numeric");

                    b.Property<string>("CodeOrder")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("CountProductJoy")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LoyaltyTransactionHistoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("TgUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Guid");

                    b.HasIndex("LoyaltyTransactionHistoryId");

                    b.ToTable("LoyaltyOrders");
                });

            modelBuilder.Entity("Business.Data.Models.LoyaltyProduct", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CountJoy")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Guid");

                    b.ToTable("LoyaltyProducts");
                });

            modelBuilder.Entity("Business.Data.Models.LoyaltySetting", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<decimal>("PriceValue")
                        .HasColumnType("numeric");

                    b.HasKey("Guid");

                    b.ToTable("LoyaltySettings");
                });

            modelBuilder.Entity("Business.Data.Models.LoyaltyTransactionHistory", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Guid");

                    b.HasIndex("UserId");

                    b.ToTable("LoyaltyTransactionHistories");
                });

            modelBuilder.Entity("Business.Data.Models.News", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FilePathImage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Guid");

                    b.ToTable("News");
                });

            modelBuilder.Entity("Business.Data.Models.Order", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ProductTransactionHistoryGuid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductTransactionItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("TgUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Guid");

                    b.HasIndex("ProductTransactionHistoryGuid");

                    b.HasIndex("ProductTransactionItemId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Business.Data.Models.OrderProductItem", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Discount")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Pirce")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.HasKey("Guid");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrdersProductItems");
                });

            modelBuilder.Entity("Business.Data.Models.PriceSettingSubscription", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Percent")
                        .HasColumnType("numeric");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid");

                    b.HasKey("Guid");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("PriceSettings");
                });

            modelBuilder.Entity("Business.Data.Models.Product", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DiscountDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DiscountPercent")
                        .HasColumnType("text");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("PriceTr")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PriceUa")
                        .HasColumnType("numeric");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uuid");

                    b.HasKey("Guid");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Business.Data.Models.ProductTransactionHistory", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.HasKey("Guid");

                    b.ToTable("ProductTransactionHistories");
                });

            modelBuilder.Entity("Business.Data.Models.ProductTransactionItem", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProductTransactionHistoryId")
                        .HasColumnType("uuid");

                    b.HasKey("Guid");

                    b.HasIndex("ProductTransactionHistoryId");

                    b.ToTable("ProductTransactionItems");
                });

            modelBuilder.Entity("Business.Data.Models.Role", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Guid");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Business.Data.Models.Section", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FilePathImage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Guid");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("Business.Data.Models.SectionsProducts", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uuid");

                    b.HasKey("Guid");

                    b.HasIndex("ProductId");

                    b.HasIndex("SectionId");

                    b.ToTable("SectionsProducts");
                });

            modelBuilder.Entity("Business.Data.Models.Setting", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("EmailPsStore")
                        .HasColumnType("text");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordPsStore")
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Guid");

                    b.HasIndex("UserId");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("Business.Data.Models.SettingPrice", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Percent")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Guid");

                    b.ToTable("SettingsPrice");
                });

            modelBuilder.Entity("Business.Data.Models.Subscription", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CusaCodeTr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CusaCodeUa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Duration")
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Platform")
                        .HasColumnType("text");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("SectionName")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Guid");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("Business.Data.Models.User", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CartId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FavoriteId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LoyaltyCurrencyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProductTransactionHistoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("TgUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Guid");

                    b.HasIndex("CartId")
                        .IsUnique();

                    b.HasIndex("FavoriteId")
                        .IsUnique();

                    b.HasIndex("LoyaltyCurrencyId")
                        .IsUnique();

                    b.HasIndex("ProductTransactionHistoryId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Business.Data.Models.AddOn", b =>
                {
                    b.HasOne("Business.Data.Models.Game", "Game")
                        .WithMany("AddOns")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Business.Data.Models.GroupAddOn", null)
                        .WithMany("AddOns")
                        .HasForeignKey("GroupAddOnGuid");

                    b.HasOne("Business.Data.Models.Product", "Product")
                        .WithOne("AddOn")
                        .HasForeignKey("Business.Data.Models.AddOn", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Business.Data.Models.Admin", b =>
                {
                    b.HasOne("Business.Data.Models.Role", "Role")
                        .WithMany("Admins")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Business.Data.Models.CartItem", b =>
                {
                    b.HasOne("Business.Data.Models.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Business.Data.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Business.Data.Models.Edition", b =>
                {
                    b.HasOne("Business.Data.Models.Game", "Game")
                        .WithMany("Editions")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Business.Data.Models.Product", "Product")
                        .WithOne("Edition")
                        .HasForeignKey("Business.Data.Models.Edition", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Business.Data.Models.FavoriteItem", b =>
                {
                    b.HasOne("Business.Data.Models.Favorite", "Favorite")
                        .WithMany("FavoriteItems")
                        .HasForeignKey("FavoriteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Business.Data.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Favorite");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Business.Data.Models.GenersToEdition", b =>
                {
                    b.HasOne("Business.Data.Models.Edition", "Edition")
                        .WithMany("EditionGeners")
                        .HasForeignKey("EditionGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Business.Data.Models.Geners", "Geners")
                        .WithMany("Editions")
                        .HasForeignKey("GenersGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Edition");

                    b.Navigation("Geners");
                });

            modelBuilder.Entity("Business.Data.Models.LoyaltyOrder", b =>
                {
                    b.HasOne("Business.Data.Models.LoyaltyTransactionHistory", "LoyaltyTransactionHistory")
                        .WithMany("LoyaltyOrders")
                        .HasForeignKey("LoyaltyTransactionHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoyaltyTransactionHistory");
                });

            modelBuilder.Entity("Business.Data.Models.LoyaltyTransactionHistory", b =>
                {
                    b.HasOne("Business.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Business.Data.Models.Order", b =>
                {
                    b.HasOne("Business.Data.Models.ProductTransactionHistory", null)
                        .WithMany("Orders")
                        .HasForeignKey("ProductTransactionHistoryGuid");

                    b.HasOne("Business.Data.Models.ProductTransactionItem", "ProductTransactionItem")
                        .WithMany("Orders")
                        .HasForeignKey("ProductTransactionItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductTransactionItem");
                });

            modelBuilder.Entity("Business.Data.Models.OrderProductItem", b =>
                {
                    b.HasOne("Business.Data.Models.Order", "Order")
                        .WithMany("OrderProductItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Business.Data.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Business.Data.Models.PriceSettingSubscription", b =>
                {
                    b.HasOne("Business.Data.Models.Subscription", "Subscription")
                        .WithMany("PriceSettingSubscriptions")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("Business.Data.Models.ProductTransactionItem", b =>
                {
                    b.HasOne("Business.Data.Models.ProductTransactionHistory", "ProductTransactionHistory")
                        .WithMany()
                        .HasForeignKey("ProductTransactionHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductTransactionHistory");
                });

            modelBuilder.Entity("Business.Data.Models.SectionsProducts", b =>
                {
                    b.HasOne("Business.Data.Models.Product", "Product")
                        .WithMany("Sections")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Business.Data.Models.Section", "Section")
                        .WithMany("Products")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("Business.Data.Models.Setting", b =>
                {
                    b.HasOne("Business.Data.Models.User", "User")
                        .WithMany("Settings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Business.Data.Models.Subscription", b =>
                {
                    b.HasOne("Business.Data.Models.Product", "Product")
                        .WithOne("Subscription")
                        .HasForeignKey("Business.Data.Models.Subscription", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Business.Data.Models.User", b =>
                {
                    b.HasOne("Business.Data.Models.Cart", "Cart")
                        .WithOne("User")
                        .HasForeignKey("Business.Data.Models.User", "CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Business.Data.Models.Favorite", "Favorite")
                        .WithOne("User")
                        .HasForeignKey("Business.Data.Models.User", "FavoriteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Business.Data.Models.LoyaltyCurrency", "LoyaltyCurrency")
                        .WithOne("User")
                        .HasForeignKey("Business.Data.Models.User", "LoyaltyCurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Business.Data.Models.ProductTransactionHistory", "ProductTransactionHistory")
                        .WithOne("User")
                        .HasForeignKey("Business.Data.Models.User", "ProductTransactionHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Favorite");

                    b.Navigation("LoyaltyCurrency");

                    b.Navigation("ProductTransactionHistory");
                });

            modelBuilder.Entity("Business.Data.Models.Cart", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("User")
                        .IsRequired();
                });

            modelBuilder.Entity("Business.Data.Models.Edition", b =>
                {
                    b.Navigation("EditionGeners");
                });

            modelBuilder.Entity("Business.Data.Models.Favorite", b =>
                {
                    b.Navigation("FavoriteItems");

                    b.Navigation("User")
                        .IsRequired();
                });

            modelBuilder.Entity("Business.Data.Models.Game", b =>
                {
                    b.Navigation("AddOns");

                    b.Navigation("Editions");
                });

            modelBuilder.Entity("Business.Data.Models.Geners", b =>
                {
                    b.Navigation("Editions");
                });

            modelBuilder.Entity("Business.Data.Models.GroupAddOn", b =>
                {
                    b.Navigation("AddOns");
                });

            modelBuilder.Entity("Business.Data.Models.LoyaltyCurrency", b =>
                {
                    b.Navigation("User")
                        .IsRequired();
                });

            modelBuilder.Entity("Business.Data.Models.LoyaltyTransactionHistory", b =>
                {
                    b.Navigation("LoyaltyOrders");
                });

            modelBuilder.Entity("Business.Data.Models.Order", b =>
                {
                    b.Navigation("OrderProductItems");
                });

            modelBuilder.Entity("Business.Data.Models.Product", b =>
                {
                    b.Navigation("AddOn");

                    b.Navigation("Edition");

                    b.Navigation("Sections");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("Business.Data.Models.ProductTransactionHistory", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("User")
                        .IsRequired();
                });

            modelBuilder.Entity("Business.Data.Models.ProductTransactionItem", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Business.Data.Models.Role", b =>
                {
                    b.Navigation("Admins");
                });

            modelBuilder.Entity("Business.Data.Models.Section", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Business.Data.Models.Subscription", b =>
                {
                    b.Navigation("PriceSettingSubscriptions");
                });

            modelBuilder.Entity("Business.Data.Models.User", b =>
                {
                    b.Navigation("Settings");
                });
#pragma warning restore 612, 618
        }
    }
}
